### ISSUE TITLE
error when importing udim textures with a single udim

### ISSUE THREAD

**Issue by blackstonecelestite** [CrisDoesCG/PBR-Express#4] opened 2024-06-19 14:01 UTC
hi, I've been trying to edit your script in these days without success. I've noticed that if I try to import a texture set that is maybe in my fifth string but only a column (so maybe .1041) the script says "seems like none of the selected files could be matched...". I managed to manually solve the problem by deleting the udim number from the texture files but this small issue really slow down the process.
Btw awesome work and thank you for making the script public

**Comment by CrisDoesCG** [comment] 2024-06-19 15:25
Hi @blackstonecelestite, thank you for your kind words.

1. Can you upload a picture or the file names which throw the error? Something like this would be enough 
![image](https://github.com/CrisDoesCG/PBR-Express/assets/151556735/66024928-f1a8-4517-8b87-151d7e4046d6)

2. [This _might_ be a quick fix.](https://github.com/CrisDoesCG/PBR-Express/tree/file-processing-rework) It's the "newest version" of the tool that I have been updating for the last couple of months, but since it still is in development and still has some issues, I haven't put it on the main GitHub page yet. Try this one out and see if it fixes the problem. This version has quite more features, which [you can read here about.](https://github.com/CrisDoesCG/PBR-Express/commits/file-processing-rework/) Still, this is a work in progress type thing, so sorry for any bugs you might encounter. I am close to getting it to be stable, just hadn't had the time recently to fully dive in and iron out the last remaining bugs.

**Comment by blackstonecelestite** [comment] 2024-06-19 16:25
this is the kind of textures I'm using. If i have something like "tire_geo_plastic_mtl_BaseColor_ACES.1041" the warning shows up, if I remove the .1041 the texture will be imported correctly. Otherwise if I have a complete udim set, something like "tire_geo_plastic_mtl_BaseColor_ACES.1041-1049" I don't have any issues and the script runs smoothly.
![Immagine 2024-06-19 181828](https://github.com/CrisDoesCG/PBR-Express/assets/173275716/a8a970f6-db9b-49c5-b3d4-e4adf0504049)
btw thanks for your fast reply and kindness, I'll try the wip version you linked. I'm slowly switching to houdini so I'm sorry if I'm not able to provide a more accurate description of the issue.

**Comment by CrisDoesCG** [comment] 2024-10-07 12:03
Hi, sorry it took so long, but the issue is resolved with the latest [version of the script](https://github.com/CrisDoesCG/PBR-Express/pull/5).

**Closed as completed by CrisDoesCG** 2024-10-07 12:03 UTC
